### ISSUE TITLE
[proposta] rename category `Hugo` to `Static Site Generator`

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari-md#101]
Che ne dite di rinominare la [categoria `Hugo`](https://tansignari.opendatasicilia.it/ricette/hugoserver/) in `Static Site Generator`? 

Secondo me "Hugo" come nome categoria è estremamente specifico (un po' come se creassimo una categoria per miller, una per visidata, una per csvkit...). Dopo aver rinominato tale categoria, potremmo anche pensare di inserire delle ricette su mkdocs o quarto ;)

cc @aborruso @pigreco

**Comment by aborruso** [comment]
> Che ne dite di rinominare la categoria Hugo in Static Site Generator?

Concordo!

> quarto

cosa è quarto?

**Comment by dennisangemi** [comment]
Mi prendo la briga di committare questa modifica senza fare PR visto il nulla osta. Spero di non fare danno ;)

**Comment by dennisangemi** [comment]
è andato tutto bene! https://tansignari.opendatasicilia.it/ricette/staticsitegenerator/
