### ISSUE TITLE
Applicazione per mettere online un test con Hugo server

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari-md#12]
Buongiorno, come faccio a mettere online un test di tansignari che uso in locale con Hugo server?  A sviluppo completato verrà rimosso. 
Non ricordo l'indirizzo che @aborruso ci hai mostrato

**Comment by aborruso** [comment]
@gbvitrano puoi usare queste informazioni https://www.docsy.dev/docs/deployment/#deployment-with-netlify

Come `HUGO_VERSION` inserisci `0.64.1`

Questi i miei setting

![image](https://user-images.githubusercontent.com/30607/74328685-a52b6200-4d8e-11ea-88d3-0f84863db6db.png)

**Comment by gbvitrano** [comment]
Ci sono riuscito :-) 
[tansignari-md-test-gb.netlify.com](https://tansignari-md-test-gb.netlify.com/)

**Comment by aborruso** [comment]
@gbvitrano non ti resta che inserire una ricetta su come fare il deploy di un sito docsy su netlify qui https://festive-bohr-4ac225.netlify.com/ricette/tansignari/
