### ISSUE TITLE
aggiunta dei tags, issue e autore nel front matter nelle ricette caricate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#16]
ci penso io

**EDIT**

```title: "Creare database spaziale da riga di comando"
linkTitle: "Creare database spaziale da riga di comando"
date: 2019-03-07
description: >
  Crea un database SpatiaLite con geotabella partendo da un file CSV con coordinate..
tags:
- sqlite
- spatialite
issue: 15
autore: "Andrea Borruso"
chef: "Totò Fiandaca"
```

**Comment by aborruso** [comment]
GRAZIE

**Comment by pigreco** [comment]
facendo riferimento alla #17 
aggiungerò nel front matter, contemporaneamente ai tags, il numero di `issue` e `autore`

**Comment by aborruso** [comment]
Grazie mille

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il ven 14 feb 2020, 14:15 Salvatore Fiandaca <notifications@github.com> ha
scritto:

**Comment by pigreco** [comment]
@aborruso 
nel caso di più valori (`issue` e `chef`) come fare??

![image](https://user-images.githubusercontent.com/7631137/74538246-14928480-4f3c-11ea-8e4d-c6ad623e12b1.png)

**Comment by aborruso** [comment]
Così

```
title: "uMap - Tematizzare i poligoni"
linkTitle: "uMap - Tematizzare i poligoni"
date: 2019-06-14
description: >
  Trucco per tematizzare poligoni in `uMap`.
tags:
- uMap
- mappe
autore: "gbvitrano"
chef: ["Andrea Borruso","Pippo Baudo"]
```

**Comment by pigreco** [comment]
![tansignaretags](https://user-images.githubusercontent.com/7631137/74549101-5678f600-4f4f-11ea-87c8-d53960cbd37c.gif)
