### ISSUE TITLE
Inserire immagini mancanti in una ricetta

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari-md#22]
Caro @gbvitrano le immagini che si vedono [qui](http://tansignari.opendatasicilia.it/it/latest/ricette/script/Google%20sheet%20IMPORTDATA()%20modificare%20la%20frequenza%20di%20aggiornamento.html), non sono visibili [qui](https://festive-bohr-4ac225.netlify.com/ricette/script/google-sheet-importdata-modificare-la-frequenza-di-aggiornamento/).

C'è probabilmente da copiarle e inserirle nella struttura di docsy

**Comment by aborruso** [comment]
@gbvitrano se hai fatto, chiudi per favore

**Comment by gbvitrano** [comment]
Ricetta corretta :-=
