### ISSUE TITLE
rimuovere vecchio blocco

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#23]
Parecchie ricetta hanno ancora il vecchio blocco (`issue`, `autore` e `ingedienti`):
![image](https://user-images.githubusercontent.com/7631137/76700586-4a509780-66b9-11ea-999a-a6276711bd78.png)

**Comment by pigreco** [comment]
@aborruso 
posso farlo io manualmente, se vuoi non perderci tempo nello script!

**Comment by pigreco** [comment]
@aborruso 

ho fatto tutto in locale, provvedo a sincronizzare!

Ho aggiunto, dove mancava, riferimenti utili aggiungendo gli ingredienti

**Comment by aborruso** [comment]
Sei un grande

**Comment by pigreco** [comment]
qualcosa è andato storto
non tutte le ricette sono sistemati
rivedo tutto
