### ISSUE TITLE
[tags] con spazi non vengono visualizzate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#24]
Tags come `riga di comando`, `overpass turbo` non sono visualizzate nelle varie ricette, ma compaioni nella lista complessiva dei tags:

https://festive-bohr-4ac225.netlify.com/tags/

---
**EDIT**

tags usati con spazi:
- feed rss;
- fixed width;
- google maps;
- Hugo server;
- overpass turbo;
- riga di comando;
- vs code

**Comment by aborruso** [comment]
Risolto con [questo](https://github.com/opendatasicilia/tansignari-md/commit/438559d851701d67d93c8062c177603ad7e7299d).

Grazie
