### ISSUE TITLE
Creare sezione FAQ

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#25]

**Comment by pigreco** [comment]
Domande:
1. Come chiedo aiuto??
2. Come scrivo ricetta??
3. Cosa posso chiedere a T'ansignari??
4. Che cosa è lo spazio T'ansignari??
5. Perché è importante leggere il Galateo di T'ansignari??

**Comment by aborruso** [comment]
@pigreco la chiudo. La miglioreremo, ma c'è

Grazie
