### ISSUE TITLE
Definire corretto posizionamento file traduzione elementi interfaccia

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari-md#27]

**Comment by aborruso** [comment]
La cartella i18n va messa nella root

![image](https://user-images.githubusercontent.com/30607/77246660-cef76480-6c29-11ea-913b-3f7a3eda19ec.png)

**Comment by gbvitrano** [comment]
ok, grazie, ora provo a spostare anche le icone  ed il logo
