### ISSUE TITLE
Alcune ricette sono Pull Request e non issue

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#32]
per esempio questa:

https://festive-bohr-4ac225.netlify.com/ricette/mappe/estrarre_punti_di_interesse_da_osm/

come mettiamo in `issue` ??

**Comment by aborruso** [comment]
In questi casi, per la prima release, metterei in testa alla ricetta, prima della descrizione "**PR di riferimento**: #35"
