### ISSUE TITLE
idea - logo per gli chefs

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#43]
Attualmente gli chefs sono 8, di questi 6 sono di ODS

da cosi:

![image](https://user-images.githubusercontent.com/7631137/80312670-aba27500-87e6-11ea-8d42-3401e319c5c3.png)

a

![image](https://user-images.githubusercontent.com/7631137/80312744-43a05e80-87e7-11ea-9e09-8fd1d0556d5f.png)

**Comment by aborruso** [comment]
mmm, non mi convince. Dobbiamo chiedere a ognuno "a chi appartiene?"

Io trasformerei questa tua proposta, in una scheda autore, con un link dopo l'icona del cuoco, che racconta un po' dell'autore.

Ma conserverei questa cosa, per la release 2

**Comment by pigreco** [comment]
> Ma conserverei questa cosa, per la release 2

ok, idea buona
aspettiamo la release 2
chiudo
