### ISSUE TITLE
come lanciare hugo

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/tansignari-md#5]
Ho installato hugo seguendo issue #4 

come avviarlo??

**Comment by aborruso** [comment]
Vai in una cartella in cui c'è un sito basato su hugo, come questo repo, apri la shell e lancia `hugo server`

Poi apri Firefox e lancia l'URL che hugo ti proporrà (di solito localhost:1313)

**Comment by pigreco** [comment]
caro @aborruso 
ho clonato questo repo e lanciato `hugo server` dalla cartella `tansignari-md`, ecco cosa accade:

![image](https://user-images.githubusercontent.com/7631137/74182753-ee22cf80-4c43-11ea-9a93-10d590dcb5c9.png)

**Comment by aborruso** [comment]
@pigreco ho modificato la risposta precedente, avevo dimenticato di aggiungere un'istruzione. Dentro docsy, ci sono dei sub repository, che devono essere prima clonati.

**Comment by pigreco** [comment]
Perfetto, funziona tutto!

grazie
