### ISSUE TITLE
Rinominare "Autori"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari-md#50]
Cari @gbvitrano @pigreco e @cirospat in t'ansignari ci sono due figure: chi scrive le ricette, dopo avere avuto una risposta a una domanda e chi ha dato le risposte giuste.

Per ora li abbiamo chiamati Autori e Chef. Ma il primo è solo al maschile e non mi  piace, e non voglio nemmeno imbruttire l'interfaccia.

Il problema è sopratutto nel menu, in cui c'è un Autor* che è un non senso, un errore.
Usando il jolly sarebbe infatti Aut*. Ma è inconprensibile.
E Autori/rici o Autrici/ori è orrendo.

Cambierei Autori e Chef in, Chef e Guide.

Gli/le chef cucinano e le guide guidano :) Mi sembra perfetto

![image](https://user-images.githubusercontent.com/30607/81469798-5c494500-91e7-11ea-8c13-dff049d140c7.png)

**Comment by pigreco** [comment]
caro @aborruso, 
per me è +1

grazie

**Comment by cirospat** [comment]
@aborruso  trovo la tua soluzione idonea a soddisfare i generi,
e quindi approvo con gusto :)
