### ISSUE TITLE
Creare moduli di raccolta dati geografici online con ONA

### ISSUE THREAD

**Issue by karmarkan** [opendatasicilia/tansignari-md#59]
Ciao! Vorrei segnalare questo:
Nella ricetta è scritto: "Una cosa importante per l’elemento “mappa” è dare all’elemento “mappa” il seguente codice nel campo “Appearance (Advanced):” maps hide-input. Questo permetterà a chi usa il modulo di posizionare il puntatore anche manualmente sulla mappa per una localizzazione precisa, nel caso in cui il gps dello smartphone/tablet/dispositivo mobile non dovesse localizzare il punto oggetto di interesse in maniera precisa!". 
In realtà se si scrive questo nel campo e si visualizza il modulo su smartphone, scompaiono tutti i campi di inserimento lat.long, accuratezza e altitudine ma viene visualizzata solo la mappa, rendendo poco "alternativo" lo strumento nel caso, e solo nel caso, in cui non si abbia copertura gps sufficiente e valori di accuratezza inadeguati.
Sarebbe interessante trovare un modo per coniugare le due cose, individuazione del punto automatico tramite gps e, nel caso si ricavino dati di accuratezza non ottimali, scegliere il punto dalla mappa.
Forse un'alternativa sarebbe creare un xls form in cui si possa effettuare una doppia scelta di rilevazione della posizione, un'opzione "tradizionale" ed una seconda in cui si visualizza la mappa nel caso la prima non sia soddisfacente.

 aggiornamento: non avevo notato la linguetta avendo in precedenza un caricamento "completo".
Poichè non di immediata visualizzazione ritengo forse ancora valida la scelta di avere le due schermate in chiaro, quella della mappa che appare come opzione di una domanda "Scegli il punto sulla mappa" da caricare come xls forms e quella di default che appare senza commentare appearance.

**Comment by aborruso** [comment]
> Forse un'alternativa sarebbe creare un xls form in cui si possa effettuare una doppia scelta di rilevazione della posizione, un'opzione "tradizionale" ed una seconda in cui si visualizza la mappa nel caso la prima non sia soddisfacente.

Buongiorno e benvenuta/o

Ciao, perché non ci fai una proposta di modifica del testo?

https://github.com/opendatasicilia/tansignari-md/edit/master/content/it/ricette/Opendatakit/ona/index.md

Grazie

**Comment by gbvitrano** [comment]
Ciao, non capisco cosa sparisce, è sempre tutto li. Basta trascinare verso destra la linguetta vicino la mappa 
![image](https://user-images.githubusercontent.com/20488693/141991527-7142b438-1b0d-4c35-92c2-192b03fab6ba.png)

![image](https://user-images.githubusercontent.com/20488693/141991586-b7e11b2a-e7bd-4f8f-9d58-58067cbcbd50.png)

**Comment by karmarkan** [comment]
oopsss non avevo notato... la presenza della linguetta, seguirò comunque strada della doppia opzione per maggiore chiarezza di visualizzazione su iphone..
Grazie ;-)

**Comment by aborruso** [comment]
@karmarkan a noi fa tanto piacere se poi ci mostri gli esiti del lavoro che stai facendo.

Senza impegno e grazie

**Comment by karmarkan** [comment]
> Ciao, non capisco cosa sparisce, è sempre tutto li. Basta trascinare verso destra la linguetta vicino la mappa ![image](https://user-images.githubusercontent.com/20488693/141991527-7142b438-1b0d-4c35-92c2-192b03fab6ba.png)
> 
> ![image](https://user-images.githubusercontent.com/20488693/141991586-b7e11b2a-e7bd-4f8f-9d58-58067cbcbd50.png)
<img width="375" alt="File 16-11-21, 16 38 08" src="https://user-images.githubusercontent.com/77639037/142016756-1e538796-30c6-4966-b606-1d052dda557d.png">

Ecco perchè non notata prima, :-))), con lo scorrimento è nascosta sotto la linguetta principale

**Comment by karmarkan** [comment]
> @karmarkan a noi fa tanto piacere se poi ci mostri gli esiti del lavoro che stai facendo.
> 
> Senza impegno e grazie

Certo, sarà un immenso piacere anche per me :-)

**Comment by karmarkan** [comment]
Buongiorno!
Alla fine ho risolto in questo modo, dato che la maniglia durante lo scorrimento della pagina su uno smartphone potrebbe non essere immediatamente visibile.
Come scrivevo ho una doppia opzione, localizzami o punta sulla mappa, quest'ultima da utilizzare nel caso in cui i dati di accuratezza siano superiori a n metri per la scarsità di segnale gps.

Questo quanto contenuto nel foglio survey:


![Schermata 2021-11-18 alle 11 41 46](https://user-images.githubusercontent.com/77639037/142400631-0662f66e-8a4f-4e76-9944-7ecea5074494.png)

e questo nel foglio choises

![Schermata 2021-11-18 alle 11 42 10](https://user-images.githubusercontent.com/77639037/142400771-071e9f73-b4f1-4222-b503-509b3039f295.png)


Sarebbe interessante far apparire la seconda opzione in automatico impostando il numero di metri minimo ricavato da accuracy, si accettano suggerimenti..
