### ISSUE TITLE
Permessi per commit

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/tansignari-md#6]
@aborruso quando ti è possibile puoi controllare i miei permessi su repo? 
I commit che faccio con l'applicazione desktop non arrivavo :-(

**Comment by aborruso** [comment]
Prova ora, scusami

**Comment by gbvitrano** [comment]
Forse devi autorizzare il vecchio commit dal pc non mi dafail da aggiornare

**Comment by gbvitrano** [comment]
Adesso funziona, Grazie grazie :-)
