### ISSUE TITLE
Info utili per scrivere una ricetta

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari-md#62]
Buongiorno!

Ho appena scritto una ricetta e ho riscontrato alcune "criticità" che potrebbero intimidire eventuali nuovi chef:

- In quale repo bisogna eseguire l'upload della ricetta in .md? Risposta: https://github.com/opendatasicilia/tansignari-md . Forse conviene specificarlo in [questa guida](https://tansignari.opendatasicilia.it/ricette/tansignari/come_scrivere_una_ricetta/) 

- [FAQ] [Cosa occorre per scrivere una ricetta](https://tansignari.opendatasicilia.it/faq/#faq). La risposta attualmente è così formulata:
> Puoi scrivere una ricetta se hai un account Github, altrimenti devi crearlo. È necessario utilizzare un Editor di testi avanzato (Visual Studio Code, Sublime Text, Atom, Notepad++, ecc…).

In realtà sarebbe possibile scrivere una ricetta anche senza utilizzare _Editor di testi avanzato_ . Basta usare l'interfaccia di GitHub. Sbaglio?

**Comment by pigreco** [comment]
Ciao @dennisangemi,
il problema relativo a quale repo utilizzare è dovuto al fatto che dovremmo utilizzare un solo repo e non due, ma ancora non troviamo il tempo per sistemare tutto;

Esatto, è possibile usare anche solo GitHub, aggiorno la FAQ

GRAZIE

**Comment by dennisangemi** [comment]
Ciao @pigreco , sorry se rispondo solo adesso. Grazie per aver modificato le faq. Chiudo questa issue e ne apro una per capire se e come fondere i due repo.
