### ISSUE TITLE
edit sezione guide

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari-md#68]
Buon pomeriggio! Vorrei modificare un piccolo dettaglio nel testo di [questa pagina](https://tansignari.opendatasicilia.it/guide/) ma non riesco a trovare il file md da modificare. Qualcuno riesce a darmi una mano? grazie!

**Comment by aborruso** [comment]
Ciao @dennisangemi perdona la lentezza. Ma il periodo è quello che è.

https://github.com/opendatasicilia/tansignari-md/blob/master/layouts/_default/guida.terms.html

**Comment by dennisangemi** [comment]
Ciao @aborruso , grazie (e non preoccuparti della lentezza). Ho fatto una PR ;) https://github.com/opendatasicilia/tansignari-md/pull/74
