### ISSUE TITLE
Migrazione contenuti

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/tansignari-md#8]
Cari tutti,
vi propongo di annunciare la presa in carico delle sezioni da migrare, con un nuova issue, in modo tale che chi lavora su "A riga di comando", non lo faccia in contemporanea con un altro, che non si duplichi lo sforzo e che non si facciano casini git.

E a poco a poco andiamo "marcando" la cosa qui.

- [x] A riga di comando
- [x] Bash
- [x] CVS (Comma-separated values)
- [x] FeedRss
- [x] Geocoder
- [x] GitHub
- [x] Mappe
- [x] Open Data Kit
- [x] Query
- [x] Read the Docs
- [x] Regex
- [x] Scraping
- [x] Script
- [x] Sqlite
- [x] Utilities

**Comment by gbvitrano** [comment]
Buongiorno, visto che ci posso lavorare oggi e poi sabato, tutta la migrazione delle ricette la volevo fare oggi. Se per voi va bene. Così durante le terapie studio la parte html

**Comment by aborruso** [comment]
@gbvitrano tu per favore, blocco per blocco, vacci avvisando con una issue.

Puoi mettere credo il check anche tu qui a migrazione di sezione fatta.

Grazie

**Comment by pigreco** [comment]
Ho aggiunto al repository `tansignari` due ricette contrassegnate con `-- in construzione` (entrambe nella categoria **Utilities**) e mi sembra che sono state portate nel nuovo repo.

1. https://github.com/opendatasicilia/tansignari/blob/master/ricette/utilities/come_usare_matrice_pendolarismo_ISTAT11.md
2. https://github.com/opendatasicilia/tansignari/blob/master/ricette/utilities/da_md_a_pdf_serie.md

Forse è meglio non caricarle nel repo se non sono ultimate??

**Comment by gbvitrano** [comment]
> 
> 
> Ho aggiunto al repository `tansignari` due ricette contrassegnate con `-- in construzione` (entrambe nella categoria **Utilities**) e mi sembra che sono state portate nel nuovo repo.
> 
>     1. https://github.com/opendatasicilia/tansignari/blob/master/ricette/utilities/come_usare_matrice_pendolarismo_ISTAT11.md
> 
>     2. https://github.com/opendatasicilia/tansignari/blob/master/ricette/utilities/da_md_a_pdf_serie.md
> 
> 
> Forse è meglio non caricarle nel repo se non sono ultimate??

Si ho visto ieri sera, avevo copiato in blocco, le cancello :-)

**Comment by cirospat** [comment]
buongiorno,
io se posso scrivere ricette in MD su Github come fatto finora con le ricette di RTD, allora continuo tranquillamente, e a questo punto confermatemi - please - se devo scriverle in questo repo **https://github.com/opendatasicilia/tansignari-md** e non più nell'altro (credo di aver capito questo).

Se scrivere ricette nel nuovo ambiente repo Github comporta l'usare la `riga di comando` (ma credo non sia requisito indispensabile per questo fine) allora non posso più dare contributi. 

Ma credo di rientrare nella prima ipotesi :)

**Comment by aborruso** [comment]
@cirospat potrai tranquillamente usare i file markdown e sarà più semplice tutta la parte della struttura.

Per ora scrivi ancora nel vecchio, perché dobbiamo scrivere soltanto una nota di poche righe sul come procedere: qual è la cartella delle ricette, e cosa scrivere nelle prime righe delle ricette (ci sono da mettere una sorta di metadati).

**Comment by cirospat** [comment]
> Per ora scrivi ancora nel vecchio

Ok grazie, buon lavoro

**Comment by gbvitrano** [comment]
> 
> 
> > Per ora scrivi ancora nel vecchio
> 
> Ok grazie, buon lavoro

@cirospat  Apri issue qui e avvisi cosa aggiungi, cosi li sposto :-)

**Comment by cirospat** [comment]
aspettate

Andrea mi dice: _Per ora scrivi ancora nel vecchio_
Tu Gianni  mi dici: _Apri issue qui e avvisi cosa aggiungi, cosi li sposto :-)_

ecco mi cunfunnivi già.

**Comment by gbvitrano** [comment]
Migrazione delle ricette completata
 :-)
