### ISSUE TITLE
Indicizzazione google

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari-md#80]
Ciao @aborruso, ho visto che ieri hai dismesso URI vecchia versione #73 (grazie!)

Poco fa ho provato a cercare su google "tansignari open data sicilia" e ho ottenuto

![image](https://user-images.githubusercontent.com/77018886/181913998-37f61ade-d451-406c-a2fd-1159b0ed6526.png)

I primi due risultati rimandano alla vecchia versione e nella prima pagina non c'è nessun link che rimandi alla versione attuale. È possibile agire in qualche modo per migliorare questo aspetto?

**Comment by aborruso** [comment]
Ciao @dennisangemi proprio ieri con @gbvitrano  abbiamo fatto pulizia di un clone, che dava fastidio.

Adesso ci vorrà qualche settimana

**Comment by dennisangemi** [comment]
Grazie @aborruso e @gbvitrano ! Se avete già fatto (e bisogna solo aspettare) posso chiudere questa issue?

**Comment by aborruso** [comment]
Io l'ho chiusa per lasciarla un po' come promemoria. La chiuderei appena siamo più su.

Ma scegli tu

**Comment by dennisangemi** [comment]
D'accordo con te. Per adesso lasciamola! Grazie di tutto ;)

**Comment by gbvitrano** [comment]
Scusate ma non l'avevo vista, non sto molto al pc in questo periodo
![2022-09-25_22h20_36](https://user-images.githubusercontent.com/20488693/192163573-cec7ed06-5b9a-4374-80de-f6dcea361a31.png)

**Comment by dennisangemi** [comment]
Aggiornamenti:
![image](https://user-images.githubusercontent.com/77018886/219028806-c1f86a58-af9c-43e6-8e44-f0a40973fa00.png)

L'url vecchio è sparito (grazie!) però https://tansignari.opendatasicilia.it/ non è ancora presente nella prima pagina dei risultati di google. Ho aperto #91 per provare a migliorare la situa

**Comment by dennisangemi** [comment]
Avevo il dubbio che tansignari non venisse indicizzato da google e ora ne ho una conferma.

Ho chiesto a ChatGPT:

> Ho il dubbio che il mio sito non sia indicizzato dai motori di ricerca. Come posso verificare questa ipotesi? Esiste un tool online che fa questo lavoro?

Mi ha risposto con:

> Certo, esistono diversi strumenti online che puoi utilizzare per verificare se il tuo sito web è stato indicizzato dai motori di ricerca. Ecco alcuni suggerimenti:
> 
> 1. Usa la funzione "site:" di Google: Digita "site:tuoindirizzo.com" nella barra di ricerca di Google (sostituisci "tuoindirizzo.com" con il tuo nome di dominio). Se Google restituisce alcune pagine del tuo sito, significa che il tuo sito è stato indicizzato.
> (...)

Così ho provato a seguire questa procedura e ottenuto:
![image](https://user-images.githubusercontent.com/77018886/219883080-5f2713b8-f5f7-4756-93a3-e1c4acf2a432.png)

Mi sa proprio che non veniamo indicizzati. Idee per risolvere il problema?

**Comment by aborruso** [comment]
> Mi sa proprio che non veniamo indicizzati. Idee per risolvere il problema?

Ho attivato tansignari nella search console del padrone.

Vediamo che succede nei prossimi giorni

![image](https://user-images.githubusercontent.com/30607/219937369-09bfd68f-5642-4dcc-97c6-ce6754e17745.png)

**Comment by gbvitrano** [comment]
> > Mi sa proprio che non veniamo indicizzati. Idee per risolvere il problema?
> 
> Ho attivato tansignari nella search console del padrone.
> 
> Vediamo che succede nei prossimi giorni
> 
> ![image](https://user-images.githubusercontent.com/30607/219937369-09bfd68f-5642-4dcc-97c6-ce6754e17745.png)

Per leggere la sitemap ovvero il file .xml che contiene i link delle pagine, normalmente ci mette 24 ore, se tutto è regolare le indicizza, in caso contrario restituisce gli errori

Hugo genera in automatico il file xml della sitemap? 
Martino si, il file si trova nella cartella radice esempio per HfcQGIS https://hfcqgis.opendatasicilia.it/sitemap.xml

Ps... cmq se a breve dobbiamo passare a Martino e quindi cambierà la struttura, indicizzare ora farà solo più confusione nei motori di ricerca.
Dopo ci vorrà più tempo per ripulire la cache dei motori di ricerca

**Comment by gbvitrano** [comment]
la sitemap di [Tansignari](https://tansignari.opendatasicilia.it/sitemap.xml)

**Comment by gbvitrano** [comment]
Eccolo... cosi non verranno mai indicizzate 
![image](https://user-images.githubusercontent.com/20488693/219950057-1697b511-bfb4-40db-ad51-fbee61f485ac.png)

**Comment by gbvitrano** [comment]
Tag corretti 
![image](https://user-images.githubusercontent.com/20488693/219950351-6b9134db-3ef4-4744-8f20-f315c7eac5c8.png)

**Comment by dennisangemi** [comment]
@gbvitrano @aborruso fortissimi! Non c'è dubbio che voi siate meglio di ChatGPT ❤

Grazie grazie 

Aspettiamo qualche giorno e vediamo che succede. È un peccato non avere tansignari indicizzato, è un gioiellino

**Comment by gbvitrano** [comment]
Se non viene cambiato il tag nelle pagine html non succederà nulla 😀 bene
che vada google ci farà notare il problema 😀

Giovan Battista Vitrano - mobile - @gbvitrano

Il dom 19 feb 2023, 14:19 Dennis Angemi ***@***.***> ha
scritto:

**Comment by dennisangemi** [comment]
> Se non viene cambiato il tag nelle pagine html non succederà nulla 😀 bene che vada google ci farà notare il problema 😀 

@gbvitrano il tag lo hai modificato tu? Se no, sai come possiamo fare?

**Comment by gbvitrano** [comment]
Io non sono a casa. Cmq il
TAG si modifica dal template html.
Come dicevo ieri bisogna valutare se ora è necessario. A breve dovremmo
passare alla
nuova versione realizzata con Material e cambia la struttura delle
cartelle. Se indiciziamo ora, dopo sarà più difficoltoso ripulire la cache
dei motori di ricerca. Se la nuova versione vedrà la luce tra un anno
allora ha senzo indicizzare ora.

Ps. Anche Bing ha una console per indicizzare, eventualmente sarebbe utile
attivare un profilo anche lì.



Giovan Battista Vitrano - mobile - @gbvitrano

Il lun 20 feb 2023, 16:59 Dennis Angemi ***@***.***> ha
scritto:

**Comment by aborruso** [comment]
@dennisangemi @gbvitrano è tutto già fatto.

Aspettiamo il padrone. Fra poco avremo esiti

**Comment by dennisangemi** [comment]
Grazie @aborruso

**Comment by dennisangemi** [comment]
Aggiornamenti:

Se visitate site:tansignari.opendatasicilia.it potete notare come adesso ci siano circa 220 pagine indicizzate! 

Grazie mille a @gbvitrano e @aborruso <3

Chiudo perchè mi sembra una mission completed

**Comment by aborruso** [comment]
Grazie mille @dennisangemi per avere sollecitato la cosa. Prezioso!
