### ISSUE TITLE
Importare guide di Gaba su React e Wordpress

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari-md#90]
Sono qui https://github.com/opendatasicilia/opendatasicilia.it/discussions/categories/racconta

Secondo me vale la pena importarle anche in tansignari perchè sono molto carine. Voi che dite?

cc @aborruso @gabacode @pigreco

**Comment by aborruso** [comment]
È solo un piacere

**Comment by gabacode** [comment]
Ciao Dennis, grazie per il pensiero. Per me va bene!

**Comment by dennisangemi** [comment]
Fatto. Ricetta qui: https://tansignari.opendatasicilia.it/ricette/staticsitegenerator/sviluppare_sito_con_wordpress_e_gatsby/

Grazie a @gabacode per il prezioso contributo

**Comment by gabacode** [comment]
> Fatto. Ricetta qui: https://tansignari.opendatasicilia.it/ricette/staticsitegenerator/sviluppare_sito_con_wordpress_e_gatsby/
> 
> Grazie a @gabacode per il prezioso contributo

Grazie @dennisangemi!
