### ISSUE TITLE
Update blogpost di presentazione

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari-md#91]
Mi sono reso conto del fatto che [l'attuale blog post che presenta tansignari](https://opendatasicilia.it/2019/03/04/tansignari-e-tappeddiri-ti-devo-insegnare-a-fare-qualcosa-e-ti-devo-perdere/) non contiene link a https://tansignari.opendatasicilia.it/

Per migliorare #80 in particolare ho aggiunto qualche link perchè pare che questo aiuti lato SEO.

il nuovo testo sarebbe:
---
Molto spesso disperdiamo richieste di aiuto ("Come faccio a ...") e le relative preziose risposte in chat, social network, email.
Sono informazioni che una volta messe in circolo, dopo pochi minuti sono già "perdute", confinate in spazi ristretti che non si prestano a una condivisione di conoscenza e quasi mai indicizzati dai motori di ricerca.

Allora abbiamo creato uno [spazio](https://tansignari.opendatasicilia.it/) per mettere a fattore comune scambi di conoscenza/esperienza sui temi che ci piacciono: dati aperti, trasparenza, Linked Open Data, analisi e trasformazione di dati. Lo abbiamo chiamato "T'ansignari e t'appeddiri" (sotto un approfondimento sul nome) e per raggiungerlo, ti basterà visitare [https://tansignari.opendatasicilia.it.](https://tansignari.opendatasicilia.it/)

Il luogo principe in cui scambiare conoscenza sarà quello delle [issue](https://github.com/opendatasicilia/tansignari/issues) del repository GitHub [opendatasicilia/tansignari](https://github.com/opendatasicilia/tansignari/): qui troverai richieste di collaborazione e aiuto. Abbiamo già iniziato a popolare questo spazio quindi puoi dare un'occhiata alle [issue aperte](https://github.com/opendatasicilia/tansignari/issues) e [quelle chiuse](https://github.com/opendatasicilia/tansignari-md/issues/_wp_link_placeholder).

Il nome di questo spazio

"T'ansignari e t'appeddiri!", ti devo insegnare a fare qualcosa e ti devo perdere.

È un proverbio presente in molti dialetti italiani (in Campania ad esempio è T’aggià mbarà e tt’àggia pèrdë!), è un invito asciutto e diretto a chi riceve un insegnamento, affinché lo valorizzi e non lo disperda. È anche e soprattutto un incoraggiamento a prendersi cura del legame tra chi si sta scambiando conoscenza e esperienza.
Un/a nonno/a con sguardo "birichino" e pieno di luce lo dice a un/a nipote, a mo' di monito, per ricevere indietro due regali: lo sguardo lucente contraccambiato e constatare che l'insegnamento sia stato utile. Anche dopo anni.
Lo dice specialmente quando il/la nipotino/a non applica quanto avrebbe già dovuto apprendere dai suoi avi.

L'immagine a cui ci ispiriamo

Il galateo

E sarà un monito per chi frequenterà questo spazio 😉

Ci sono delle "buone maniere", che abbiamo costruito in questi giorni di primo uso:

prima di chiedere aiuto, cerca un po' sul web. Nel 99% dei casi la risposta esiste già ed è quella giusta;

prima di chiedere aiuto, dopo che ti sei documentato, fai comunque qualche tentativo per risolvere il tutto in autonomia. Questo ti aiuterà a scrivere in modo molto chiaro un eventuale richiesta di supporto;

documenta per bene la tua domanda. Che strumento hai usato, che versione, ecc. e allega (se puoi) uno o più file per poter replicare quanto descritto;

fai domande su temi vicini a quelli che esplora la comunità [Open Data Sicilia](http://opendatasicilia.it/): i dati aperti, la trasparenza amministrativa, il civic tech e non l'ultima ricetta di "pasta al forno", la traduzione del Moby Dick che hai letto o Blender;

nel titolo della issue per favore inserisci una "etichetta" per classificare i post (ad esempio [scripting] Come fare a rimuovere i duplicati di una tabella);

se sei soddisfatto della risposta, sei invitato a rimborsare, creando un testo, una ricetta, che racconti per bene il problema che hai riscontrato e come è possibile risolverlo (vedi sotto);

quando rispondi, fornisci gli elementi di base utili a comprendere quanto hai scritto.

Per leggere il galateo completo fai [click qui](https://tansignari.opendatasicilia.it/galateo/)!

Ricette

Le stiamo raccogliendo [qui](https://tansignari.opendatasicilia.it/ricette/) e speriamo di leggerne presto una tua. Se ti interessano i file sorgente, li trovi [questa cartella](https://github.com/opendatasicilia/tansignari-md/tree/master/content/it/ricette). Se non sai come si fa, chiedilo con una issue; non appena possibile scriveremo una guida in merito.

L'obiettivo di fondo è quello di trasformare questa raccolta in un testo ipertestuale strutturato.

Note finali

In ultimo un grazie a Andrea,  Ciro, Gianni, Nino e Salvatore, che si sono spesi a dare una prima forma a questo spazio, a viverlo, alimentarlo e sperimentarlo. 

--- 

@aborruso @picomiles @gbvitrano mi date benedizione per aggiornare il blog post e pubblicare le modifiche?

P.s.
Il testo qui incollato è privo di stile ma su wp è tutto ok

**Comment by aborruso** [comment]
Per me vai pure e grazie

**Comment by gbvitrano** [comment]
Grazie @dennisangemi anche per me vai pure :-)
